name: Scrap HDB and Mall data every hour

on:
  push:
      branches:
        - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name : Set correct time
        run: sudo timedatectl set-timezone Asia/Singapore
      - name: Run Scraper1
        run: python script1.py
      - name: Run Scraper2
        run: python script2.py
      - name: Commit files
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
        
